import React, { useState, useEffect, useMemo } from "react";
import {
  Crosshair,
  Compass,
  Radio,
  Search,
  AlertTriangle,
  Play,
  RotateCcw,
  CheckCircle2,
  ExternalLink,
  ShieldAlert,
  Car,
  MapPin,
  Maximize2,
  Layers,
  ChevronRight,
  Clock,
  Eye,
  Camera,
  Copy,
  Check,
  Share2,
  ArrowUpRight,
  Lock,
  Flame,
  Info
} from "lucide-react";
import {
  ACTIVE_PURSUIT_CASES,
  COMPASS_SECTORS_8,
  CompassSector8,
  PursuitActiveCase,
  PursuitHopNode,
  getBearingSector8,
  calculateBearingDegrees
} from "../data/pursuitTrackerData";
import { CCTVCamera } from "../types";
import { CCTV_CAMERAS } from "../data/cctvData";

interface PursuitScannerDashboardProps {
  onInspectCamera?: (camera: CCTVCamera) => void;
  userCoordinates?: { lat: number; lng: number };
}

export const PursuitScannerDashboard: React.FC<PursuitScannerDashboardProps> = ({
  onInspectCamera,
  userCoordinates
}) => {
  const [selectedCaseId, setSelectedCaseId] = useState<string>(ACTIVE_PURSUIT_CASES[0].id);
  const [activeHopIndex, setActiveHopIndex] = useState<number>(0);
  const [selectedSector, setSelectedSector] = useState<CompassSector8 | "ALL">("ALL");
  const [isLiveScanning, setIsLiveScanning] = useState<boolean>(false);
  const [scanStep, setScanStep] = useState<number>(0);
  const [scanRadarAngle, setScanRadarAngle] = useState<number>(0);
  const [copiedReport, setCopiedReport] = useState<boolean>(false);
  const [customVehicleModalOpen, setCustomVehicleModalOpen] = useState<boolean>(false);

  const currentCase =
    ACTIVE_PURSUIT_CASES.find((c) => c.id === selectedCaseId) || ACTIVE_PURSUIT_CASES[0];

  // Radar sweep animation
  useEffect(() => {
    const timer = setInterval(() => {
      setScanRadarAngle((prev) => (prev + 3) % 360);
    }, 50);
    return () => clearInterval(timer);
  }, []);

  // Multi-hop animated pursuit scan
  useEffect(() => {
    if (!isLiveScanning) return;
    const totalHops = currentCase.hops.length;

    const interval = setInterval(() => {
      setScanStep((prev) => {
        if (prev >= totalHops) {
          setIsLiveScanning(false);
          return totalHops;
        }
        setActiveHopIndex(prev);
        return prev + 1;
      });
    }, 2200);

    return () => clearInterval(interval);
  }, [isLiveScanning, currentCase]);

  const handleStartPursuitScan = () => {
    setScanStep(0);
    setActiveHopIndex(0);
    setIsLiveScanning(true);
  };

  const handleStopScan = () => {
    setIsLiveScanning(false);
  };

  const currentHop = currentCase.hops[activeHopIndex] || currentCase.hops[0];

  const handleCopyTacticalReport = () => {
    const reportText = `[LVMPD / NV-FAST 702 TACTICAL INCIDENT CONTAINMENT REPORT]
CASE NUMBER: ${currentCase.caseNumber}
CRIME: ${currentCase.crimeType}
AGENCY: ${currentCase.agencyAssigned}
INCIDENT TIME: ${currentCase.incidentTime}
ORIGIN: ${currentCase.originLocation} (${currentCase.originCoordinates.lat}, ${currentCase.originCoordinates.lng})

SUSPECT VEHICLE DESCRIPTION:
- Make/Model: ${currentCase.suspectVehicle.makeModel} (${currentCase.suspectVehicle.color})
- Year Range: ${currentCase.suspectVehicle.yearRange}
- Plate: ${currentCase.suspectVehicle.plateNumber} [${currentCase.suspectVehicle.plateNotes}]
- Distinctive Features: ${currentCase.suspectVehicle.distinctiveFeatures.join("; ")}

8-DIRECTIONAL 5-MILE MULTI-HOP CAMERA TRAIL:
${currentCase.hops
  .map(
    (h, idx) =>
      `HOP #${idx + 1} [${h.sector8} Sector - ${h.timestamp}]: Cam #${h.cameraNumber} (${h.intersection})
 - Detection Confidence: ${h.detectionConfidence}%
 - Velocity: ${h.speedMph} MPH
 - Action: ${h.turnActionTaken}
 - Snapshot Source: ${h.sourceUrl}`
  )
  .join("\n\n")}

TERMINAL LAYING-LOW CONTAINMENT ZONE:
- Zone: ${currentCase.containmentZone.zoneName}
- Sector: ${currentCase.containmentZone.sectorDescription}
- Center Coordinates: ${currentCase.containmentZone.centerCoordinates.lat}, ${currentCase.containmentZone.centerCoordinates.lng}
- Containment Probability: ${currentCase.containmentZone.containmentProbability}% (HIGH CONFIDENCE)
- Status: LAYING LOW (All downstream perimeter boundary cameras CLEARED/NEGATIVE)

TACTICAL SURVEILLANCE CHOKEPOINTS:
${currentCase.containmentZone.recommendedSurveillancePosts
  .map((p) => `- [${p.label}] at ${p.intersection}: ${p.action}`)
  .join("\n")}

Generated by Vegas Pulse 702 FAST Radar Intelligence Engine`;

    navigator.clipboard.writeText(reportText);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2500);
  };

  return (
    <div className="space-y-4 font-mono text-cyan-100 animate-in fade-in duration-150">
      {/* Top Banner & Case Selector */}
      <div className="bg-black/90 rounded-xl border border-cyan-500/40 p-4 shadow-[0_0_25px_rgba(0,240,255,0.15)] flex flex-col lg:flex-row lg:items-center justify-between gap-4 backdrop-blur-md">
        <div className="space-y-1">
          <div className="flex items-center gap-2 flex-wrap text-xs">
            <span className="w-8 h-8 rounded-lg bg-red-950 text-red-400 border border-red-500/50 flex items-center justify-center shadow-[0_0_12px_rgba(239,68,68,0.3)]">
              <Crosshair className="w-4 h-4 animate-spin text-red-400" />
            </span>
            <span className="font-bold px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-500/40">
              FAST_RADAR // 8-DIR_MULTI_HOP
            </span>
            <span className="font-bold px-2 py-0.5 rounded bg-red-950 text-red-300 border border-red-500/40">
              5-MILE PURSUIT CONFINEMENT
            </span>
            <span className="text-[11px] text-stone-400">
              bugatti.nvfast.org optical telemetry
            </span>
          </div>

          <h2 className="text-base sm:text-lg font-bold text-white tracking-wide flex items-center gap-2">
            <span>8-Directional Multi-Hop Intersection Camera Pursuit Engine</span>
          </h2>
          <p className="text-xs text-stone-300">
            Scanning historical snapshot sequences across 8 radial compass sectors to chain suspect vehicle flight paths and isolate the exact laying-low containment zone.
          </p>
        </div>

        {/* Scan Actions */}
        <div className="flex items-center gap-2 flex-wrap shrink-0">
          {isLiveScanning ? (
            <button
              type="button"
              onClick={handleStopScan}
              className="px-4 py-2 rounded-lg bg-red-600 hover:bg-red-500 text-white font-bold text-xs flex items-center gap-2 shadow-[0_0_15px_rgba(239,68,68,0.4)] transition-all animate-pulse"
            >
              <Radio className="w-4 h-4 text-white animate-ping" />
              <span>PAUSE PURSUIT SCAN</span>
            </button>
          ) : (
            <button
              type="button"
              onClick={handleStartPursuitScan}
              className="px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-black font-bold text-xs flex items-center gap-2 shadow-[0_0_15px_rgba(0,240,255,0.4)] transition-all"
            >
              <Play className="w-4 h-4 fill-current" />
              <span>EXECUTE 8-DIR 5-MILE SCAN</span>
            </button>
          )}

          <button
            type="button"
            onClick={handleCopyTacticalReport}
            className="px-3 py-2 rounded-lg bg-black/80 hover:bg-white/10 border border-cyan-500/40 text-cyan-300 text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-[0_0_10px_rgba(0,240,255,0.15)]"
            title="Copy formatted police dispatch report with containment coordinates"
          >
            {copiedReport ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-300 font-bold">REPORT COPIED</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>COPY TACTICAL REPORT</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Active Case Selector Tabs */}
      <div className="bg-black/80 rounded-xl border border-white/10 p-3 space-y-2">
        <div className="flex items-center justify-between text-xs text-stone-400">
          <span className="font-bold text-cyan-400 flex items-center gap-1.5">
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>ACTIVE OPEN CASES WITH SUSPECT VEHICLES</span>
          </span>
          <span className="text-[11px]">
            SELECT CASE TO CALCULATE TRAJECTORY VECTORS
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
          {ACTIVE_PURSUIT_CASES.map((caseItem) => {
            const isSelected = caseItem.id === selectedCaseId;
            return (
              <button
                key={caseItem.id}
                type="button"
                onClick={() => {
                  setSelectedCaseId(caseItem.id);
                  setActiveHopIndex(0);
                  setIsLiveScanning(false);
                }}
                className={`p-3 rounded-lg border text-left transition-all relative overflow-hidden ${
                  isSelected
                    ? "bg-cyan-950/60 border-cyan-400 shadow-[0_0_15px_rgba(0,240,255,0.25)]"
                    : "bg-black/50 border-white/10 hover:border-cyan-500/50 hover:bg-white/5"
                }`}
              >
                {isSelected && (
                  <div className="absolute top-0 right-0 w-2 h-2 bg-cyan-400 rounded-bl" />
                )}
                <div className="flex items-center justify-between text-[11px] mb-1">
                  <span className="font-mono text-cyan-300 font-bold">
                    {caseItem.caseNumber}
                  </span>
                  <span className="text-stone-400 text-[10px]">
                    {caseItem.hops.length} HOPS MAPPED
                  </span>
                </div>

                <div className="text-xs font-bold text-white truncate mb-1">
                  {caseItem.title}
                </div>

                <div className="flex items-center gap-1.5 text-[11px] text-stone-300">
                  <Car className="w-3 h-3 text-red-400 shrink-0" />
                  <span className="truncate font-semibold text-amber-300">
                    {caseItem.suspectVehicle.color} {caseItem.suspectVehicle.makeModel}
                  </span>
                </div>

                <div className="text-[10px] text-stone-400 mt-1 truncate">
                  Origin: {caseItem.originLocation.split("(")[0]}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Pursuit Grid: 8-Directional Radar & Multi-Hop Breadcrumbs */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-start">
        
        {/* Left Column: 8-Directional Radial Radar Display (5 Cols) */}
        <div className="lg:col-span-5 bg-black/90 rounded-xl border border-cyan-500/40 p-4 shadow-[0_0_25px_rgba(0,240,255,0.15)] flex flex-col items-center justify-between space-y-4 relative overflow-hidden">
          
          {/* Radar Header */}
          <div className="w-full flex items-center justify-between border-b border-cyan-500/30 pb-2.5 text-xs">
            <div className="flex items-center gap-2">
              <Compass className="w-4 h-4 text-cyan-400" />
              <span className="font-bold text-white tracking-wider">
                8-DIRECTIONAL RADIAL MATRIX
              </span>
            </div>
            <span className="text-[10px] text-cyan-400 font-bold px-1.5 py-0.5 rounded bg-cyan-950 border border-cyan-500/30">
              5-MILE RADIUS
            </span>
          </div>

          {/* Interactive SVG Radar */}
          <div className="relative w-64 h-64 sm:w-72 sm:h-72 flex items-center justify-center my-2">
            <svg
              className="w-full h-full"
              viewBox="0 0 300 300"
              style={{ filter: "drop-shadow(0 0 8px rgba(0,240,255,0.3))" }}
            >
              {/* Concentric 1 to 5 mile rings */}
              <circle cx="150" cy="150" r="140" fill="rgba(0, 20, 30, 0.4)" stroke="#00f0ff" strokeWidth="1" strokeDasharray="3,3" opacity="0.4" />
              <circle cx="150" cy="150" r="112" fill="none" stroke="#00f0ff" strokeWidth="1" strokeDasharray="3,3" opacity="0.3" />
              <circle cx="150" cy="150" r="84" fill="none" stroke="#00f0ff" strokeWidth="1" strokeDasharray="3,3" opacity="0.4" />
              <circle cx="150" cy="150" r="56" fill="none" stroke="#00f0ff" strokeWidth="1" strokeDasharray="3,3" opacity="0.5" />
              <circle cx="150" cy="150" r="28" fill="none" stroke="#00f0ff" strokeWidth="1" strokeDasharray="2,2" opacity="0.6" />

              {/* Distance Labels */}
              <text x="154" y="42" fill="#38bdf8" fontSize="8" fontFamily="monospace">5 MI</text>
              <text x="154" y="70" fill="#38bdf8" fontSize="8" fontFamily="monospace">4 MI</text>
              <text x="154" y="98" fill="#38bdf8" fontSize="8" fontFamily="monospace">3 MI</text>
              <text x="154" y="126" fill="#38bdf8" fontSize="8" fontFamily="monospace">2 MI</text>
              <text x="154" y="146" fill="#38bdf8" fontSize="8" fontFamily="monospace">1 MI</text>

              {/* 8 Cardinal & Intercardinal Axis Lines */}
              {/* N-S */}
              <line x1="150" y1="10" x2="150" y2="290" stroke="#00f0ff" strokeWidth="1" opacity="0.3" />
              {/* E-W */}
              <line x1="10" y1="150" x2="290" y2="150" stroke="#00f0ff" strokeWidth="1" opacity="0.3" />
              {/* NE-SW */}
              <line x1="51" y1="51" x2="249" y2="249" stroke="#00f0ff" strokeWidth="1" strokeDasharray="2,4" opacity="0.2" />
              {/* NW-SE */}
              <line x1="51" y1="249" x2="249" y2="51" stroke="#00f0ff" strokeWidth="1" strokeDasharray="2,4" opacity="0.2" />

              {/* Rotating Sweep Beam */}
              <line
                x1="150"
                y1="150"
                x2={150 + 140 * Math.cos((scanRadarAngle * Math.PI) / 180)}
                y2={150 + 140 * Math.sin((scanRadarAngle * Math.PI) / 180)}
                stroke="#00f0ff"
                strokeWidth="2"
                opacity="0.8"
              />

              {/* Sweep gradient arc cone */}
              <path
                d={`M 150 150 L ${150 + 140 * Math.cos(((scanRadarAngle - 30) * Math.PI) / 180)} ${
                  150 + 140 * Math.sin(((scanRadarAngle - 30) * Math.PI) / 180)
                } A 140 140 0 0 1 ${150 + 140 * Math.cos((scanRadarAngle * Math.PI) / 180)} ${
                  150 + 140 * Math.sin((scanRadarAngle * Math.PI) / 180)
                } Z`}
                fill="url(#radarGradient)"
                opacity="0.25"
              />

              <defs>
                <linearGradient id="radarGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stopColor="#00f0ff" stopOpacity="0" />
                  <stop offset="100%" stopColor="#00f0ff" stopOpacity="0.4" />
                </linearGradient>
              </defs>

              {/* Origin Incident Marker (Center) */}
              <circle cx="150" cy="150" r="5" fill="#ef4444" />
              <circle cx="150" cy="150" r="10" fill="none" stroke="#ef4444" strokeWidth="1.5" className="animate-ping" opacity="0.75" />

              {/* Multi-Hop Traversal Trail Lines between Hops */}
              {currentCase.hops.map((hop, index) => {
                // Calculate pseudo polar coordinates based on bearingDeg and distance
                const r = Math.min((hop.distanceFromOriginMiles / 5) * 140, 135);
                const angleRad = ((hop.bearingDeg - 90) * Math.PI) / 180;
                const cx = 150 + r * Math.cos(angleRad);
                const cy = 150 + r * Math.sin(angleRad);

                const prevHop = index === 0 ? null : currentCase.hops[index - 1];
                const prevR = prevHop ? Math.min((prevHop.distanceFromOriginMiles / 5) * 140, 135) : 0;
                const prevAngleRad = prevHop ? ((prevHop.bearingDeg - 90) * Math.PI) / 180 : 0;
                const prevX = prevHop ? 150 + prevR * Math.cos(prevAngleRad) : 150;
                const prevY = prevHop ? 150 + prevR * Math.sin(prevAngleRad) : 150;

                const isCurrentActive = index === activeHopIndex;

                return (
                  <g key={`hop-node-${hop.cameraNumber}`}>
                    {/* Vector arrow line */}
                    <line
                      x1={prevX}
                      y1={prevY}
                      x2={cx}
                      y2={cy}
                      stroke={isCurrentActive ? "#00f0ff" : "#f59e0b"}
                      strokeWidth={isCurrentActive ? "2.5" : "1.8"}
                      strokeDasharray={index <= activeHopIndex ? "none" : "3,3"}
                    />

                    {/* Camera Node Circle */}
                    <circle
                      cx={cx}
                      cy={cy}
                      r={isCurrentActive ? "7" : "5"}
                      fill={isCurrentActive ? "#00f0ff" : "#ef4444"}
                      stroke="#ffffff"
                      strokeWidth="1.5"
                      className="cursor-pointer"
                      onClick={() => setActiveHopIndex(index)}
                    />

                    {/* Hop Number Label */}
                    <text
                      x={cx + 8}
                      y={cy + 4}
                      fill="#ffffff"
                      fontSize="9"
                      fontWeight="bold"
                      fontFamily="monospace"
                    >
                      #{index + 1}
                    </text>
                  </g>
                );
              })}

              {/* Containment Zone Terminal Perimeter Circle */}
              {(() => {
                const terminalHop = currentCase.hops[currentCase.hops.length - 1];
                const r = Math.min((terminalHop.distanceFromOriginMiles / 5) * 140 + 12, 135);
                const angleRad = ((terminalHop.bearingDeg - 90) * Math.PI) / 180;
                const cx = 150 + r * Math.cos(angleRad);
                const cy = 150 + r * Math.sin(angleRad);

                return (
                  <g>
                    <circle
                      cx={cx}
                      cy={cy}
                      r="18"
                      fill="rgba(239, 68, 68, 0.25)"
                      stroke="#ef4444"
                      strokeWidth="2"
                      strokeDasharray="4,2"
                      className="animate-pulse"
                    />
                    <text
                      x={cx - 16}
                      y={cy + 28}
                      fill="#ef4444"
                      fontSize="8"
                      fontWeight="bold"
                      fontFamily="monospace"
                    >
                      LAY-LOW ZONE
                    </text>
                  </g>
                );
              })()}

              {/* Cardinal Sector Labels */}
              <text x="145" y="18" fill="#ffffff" fontSize="11" fontWeight="bold" fontFamily="monospace">N</text>
              <text x="240" y="55" fill="#38bdf8" fontSize="9" fontWeight="bold" fontFamily="monospace">NE</text>
              <text x="282" y="154" fill="#ffffff" fontSize="11" fontWeight="bold" fontFamily="monospace">E</text>
              <text x="240" y="255" fill="#38bdf8" fontSize="9" fontWeight="bold" fontFamily="monospace">SE</text>
              <text x="146" y="292" fill="#ffffff" fontSize="11" fontWeight="bold" fontFamily="monospace">S</text>
              <text x="50" y="255" fill="#38bdf8" fontSize="9" fontWeight="bold" fontFamily="monospace">SW</text>
              <text x="6" y="154" fill="#ffffff" fontSize="11" fontWeight="bold" fontFamily="monospace">W</text>
              <text x="48" y="55" fill="#38bdf8" fontSize="9" fontWeight="bold" fontFamily="monospace">NW</text>
            </svg>
          </div>

          {/* 8 Sector Filter Buttons */}
          <div className="w-full space-y-1">
            <span className="text-[10px] text-stone-400 block font-bold uppercase">
              SECTOR FLIGHT PATH FILTER (CLICK TO ISOLATE):
            </span>
            <div className="grid grid-cols-4 gap-1 text-[10px]">
              {COMPASS_SECTORS_8.map((s) => {
                const isSelected = selectedSector === s.sector;
                const isTrailSector = currentCase.hops.some((h) => h.sector8 === s.sector);

                return (
                  <button
                    key={s.sector}
                    type="button"
                    onClick={() =>
                      setSelectedSector((prev) => (prev === s.sector ? "ALL" : s.sector))
                    }
                    className={`p-1.5 rounded border font-mono font-bold flex items-center justify-between transition-all ${
                      isSelected
                        ? "bg-cyan-500 text-black border-cyan-400 shadow-[0_0_10px_rgba(0,240,255,0.3)]"
                        : isTrailSector
                        ? "bg-red-950/60 text-red-300 border-red-500/50 hover:border-red-400"
                        : "bg-black/40 text-stone-400 border-white/10 hover:border-white/20"
                    }`}
                  >
                    <span>
                      {s.arrow} {s.sector}
                    </span>
                    {isTrailSector && (
                      <span className="w-1.5 h-1.5 rounded-full bg-red-400 animate-ping" />
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Suspect Target Telemetry Summary Card */}
          <div className="w-full p-2.5 rounded-lg bg-black/80 border border-cyan-500/30 text-xs space-y-1">
            <div className="flex items-center justify-between text-[11px] text-amber-300 font-bold">
              <span>SUSPECT TARGET SIGNATURE:</span>
              <span className="text-stone-400">{currentCase.incidentTime}</span>
            </div>
            <div className="text-white font-bold">
              {currentCase.suspectVehicle.color} {currentCase.suspectVehicle.makeModel} ({currentCase.suspectVehicle.yearRange})
            </div>
            <div className="text-stone-300 text-[11px]">
              Plate: <span className="text-amber-400 font-mono font-bold">{currentCase.suspectVehicle.plateNumber}</span>
            </div>
            <div className="text-[10px] text-stone-400 leading-tight">
              {currentCase.suspectVehicle.distinctiveFeatures.slice(0, 2).join(" • ")}
            </div>
          </div>
        </div>

        {/* Right Column: Multi-Hop Trail, Snapshot Inspector, and Lay-Low Containment Zone (7 Cols) */}
        <div className="lg:col-span-7 space-y-4">
          
          {/* Multi-Hop Timeline Tabs */}
          <div className="bg-black/90 rounded-xl border border-cyan-500/40 p-4 shadow-[0_0_20px_rgba(0,240,255,0.15)] space-y-3">
            <div className="flex items-center justify-between border-b border-cyan-500/30 pb-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                  <Radio className="w-3.5 h-3.5 text-red-400 animate-pulse" />
                  <span>TRAJECTORY HOP PROGRESSION ({currentCase.hops.length} HOPS)</span>
                </span>
              </div>
              <span className="text-[11px] text-cyan-400 font-mono">
                ORIGIN: {currentCase.originLocation.split("(")[0]}
              </span>
            </div>

            {/* Hop Stepper Buttons */}
            <div className="flex items-center gap-2 overflow-x-auto pb-1 text-xs">
              {currentCase.hops.map((hop, idx) => {
                const isActive = idx === activeHopIndex;
                return (
                  <button
                    key={hop.cameraNumber}
                    type="button"
                    onClick={() => setActiveHopIndex(idx)}
                    className={`px-3 py-2 rounded-lg border text-left shrink-0 transition-all flex items-center gap-2 ${
                      isActive
                        ? "bg-cyan-500 text-black font-bold border-cyan-400 shadow-[0_0_12px_rgba(0,240,255,0.3)]"
                        : "bg-black/60 text-stone-300 border-white/15 hover:border-cyan-500/50 hover:text-white"
                    }`}
                  >
                    <span
                      className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                        isActive ? "bg-black text-cyan-300" : "bg-red-950 text-red-300 border border-red-500/40"
                      }`}
                    >
                      {idx + 1}
                    </span>
                    <div>
                      <div className="text-[11px] font-bold truncate max-w-[120px]">
                        Cam #{hop.cameraNumber}
                      </div>
                      <div className="text-[9px] opacity-80">
                        {hop.sector8} Sector • {hop.timestamp}
                      </div>
                    </div>
                  </button>
                );
              })}

              {/* Final Containment Zone Step Tab */}
              <button
                type="button"
                onClick={() => setActiveHopIndex(currentCase.hops.length)}
                className={`px-3 py-2 rounded-lg border text-left shrink-0 transition-all flex items-center gap-2 ${
                  activeHopIndex === currentCase.hops.length
                    ? "bg-red-600 text-white font-bold border-red-400 shadow-[0_0_15px_rgba(239,68,68,0.4)]"
                    : "bg-red-950/40 text-red-300 border-red-500/30 hover:border-red-400"
                }`}
              >
                <Lock className="w-4 h-4 text-red-400" />
                <div>
                  <div className="text-[11px] font-bold">CONTAINMENT ZONE</div>
                  <div className="text-[9px] opacity-80">LAYING-LOW SECTOR</div>
                </div>
              </button>
            </div>

            {/* Active Hop Detailed Snapshot Inspector */}
            {activeHopIndex < currentCase.hops.length ? (
              <div className="bg-black/95 rounded-lg border border-cyan-500/30 p-3 sm:p-4 space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-white/10 pb-2">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-500/40 text-[10px] font-bold">
                        HOP #{currentHop.hopNumber} OF {currentCase.hops.length}
                      </span>
                      <span className="px-2 py-0.5 rounded bg-red-950 text-red-300 border border-red-500/40 text-[10px] font-bold">
                        MATCH: {currentHop.detectionConfidence}% OPTICAL CONFIDENCE
                      </span>
                      <span className="text-[11px] text-stone-400 font-mono">
                        {currentHop.timestamp}
                      </span>
                    </div>
                    <h3 className="text-sm font-bold text-white mt-1">
                      {currentHop.intersection}
                    </h3>
                  </div>

                  <a
                    href={currentHop.sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-2.5 py-1 rounded bg-black/60 hover:bg-white/10 border border-white/20 text-cyan-300 text-xs font-semibold inline-flex items-center gap-1.5 transition-colors self-start sm:self-center"
                  >
                    <span>FAST Cam #{currentHop.cameraNumber}</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                </div>

                {/* Simulated Computer Vision Snapshot Image Card */}
                <div className="relative rounded-lg overflow-hidden border border-cyan-500/40 bg-stone-950 p-2 sm:p-3 space-y-2">
                  {/* Visual Snapshot Simulation Canvas */}
                  <div className="relative w-full h-44 sm:h-52 bg-slate-950 rounded border border-cyan-500/20 overflow-hidden flex flex-col justify-between p-3 font-mono">
                    
                    {/* Background Roadway Perspective Lines */}
                    <div className="absolute inset-0 opacity-20 pointer-events-none">
                      <div className="w-full h-full bg-[linear-gradient(to_bottom,transparent_0%,rgba(0,240,255,0.15)_100%)]" />
                      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-48 h-full border-x border-cyan-500/30" />
                      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-0.5 h-full border-r border-dashed border-cyan-500/40" />
                    </div>

                    {/* Camera OSD Overlay */}
                    <div className="relative z-10 flex items-center justify-between text-[10px] text-cyan-400 bg-black/60 px-2 py-1 rounded border border-white/10">
                      <span>NV-FAST CAM #{currentHop.cameraNumber} // {currentHop.intersection}</span>
                      <span>{currentHop.frames[0]?.timestamp || currentHop.timestamp}</span>
                    </div>

                    {/* Bounding Box on Suspect Vehicle */}
                    <div className="relative z-10 mx-auto my-auto w-48 sm:w-56 p-2 rounded border-2 border-red-500 bg-red-950/40 shadow-[0_0_15px_rgba(239,68,68,0.5)] flex flex-col items-center justify-center text-center animate-in zoom-in-95">
                      <div className="text-[9px] bg-red-600 text-white font-bold px-1.5 py-0.5 rounded -top-3 absolute font-mono uppercase tracking-wider">
                        TARGET DETECTED // {currentHop.detectionConfidence}% MATCH
                      </div>

                      <Car className="w-8 h-8 text-red-400 mb-1" />
                      <span className="text-xs font-bold text-white">
                        {currentCase.suspectVehicle.color} {currentCase.suspectVehicle.makeModel}
                      </span>
                      <span className="text-[10px] font-mono text-amber-300 font-bold">
                        PLATE: {currentCase.suspectVehicle.plateNumber}
                      </span>
                      <span className="text-[9px] text-cyan-300 mt-0.5">
                        VELOCITY: {currentHop.speedMph} MPH • {currentHop.sector8} BEARING ({currentHop.bearingDeg}°)
                      </span>
                    </div>

                    {/* Bottom Status Bar */}
                    <div className="relative z-10 flex items-center justify-between text-[10px] text-stone-400 bg-black/70 px-2 py-1 rounded">
                      <span>RADIAL SECTOR: {currentHop.sector8} ({currentHop.bearingDeg}°)</span>
                      <span className="text-emerald-400">FRAME OCR: POSITIVE</span>
                      <span>DIST FROM ORIGIN: {currentHop.distanceFromOriginMiles} MI</span>
                    </div>
                  </div>

                  {/* Turn Action & Frame Details */}
                  <div className="text-xs text-stone-200 leading-relaxed font-sans bg-black/50 p-2.5 rounded border border-white/10">
                    <span className="font-mono text-cyan-400 font-bold block mb-1">
                      ACTION TAKEN AT INTERSECTION:
                    </span>
                    {currentHop.turnActionTaken}
                  </div>
                </div>

                {/* Inspect in Global CCTV Modal */}
                {onInspectCamera && (
                  <button
                    type="button"
                    onClick={() => {
                      const matchedCam = CCTV_CAMERAS.find((c) => c.id === currentHop.cameraId);
                      if (matchedCam) onInspectCamera(matchedCam);
                    }}
                    className="w-full py-1.5 rounded bg-cyan-950 hover:bg-cyan-900 border border-cyan-500/40 text-cyan-300 text-xs font-bold flex items-center justify-center gap-1.5 transition-colors"
                  >
                    <Maximize2 className="w-3.5 h-3.5" />
                    <span>OPEN FULL SCREEN FAST OPTICAL TELEMETRY</span>
                  </button>
                )}
              </div>
            ) : (
              /* Laying Low Terminal Containment Zone Screen */
              <div className="bg-red-950/30 rounded-lg border-2 border-red-500/50 p-4 space-y-4 animate-in zoom-in-95">
                <div className="flex items-start justify-between gap-3 border-b border-red-500/30 pb-3">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="px-2.5 py-0.5 rounded bg-red-600 text-white font-bold text-xs uppercase shadow-[0_0_10px_rgba(239,68,68,0.5)]">
                        TERMINAL CONTAINMENT PINPOINTED
                      </span>
                      <span className="text-xs font-bold text-amber-300 font-mono">
                        {currentCase.containmentZone.containmentProbability}% PROBABILITY
                      </span>
                    </div>
                    <h3 className="text-base font-bold text-white">
                      {currentCase.containmentZone.zoneName}
                    </h3>
                    <p className="text-xs text-stone-300 font-sans">
                      {currentCase.containmentZone.sectorDescription}
                    </p>
                  </div>

                  <div className="text-right text-xs shrink-0">
                    <div className="text-red-400 font-bold font-mono">STATUS:</div>
                    <div className="text-white uppercase font-bold">
                      {currentCase.containmentZone.status.replace("_", " ")}
                    </div>
                  </div>
                </div>

                {/* Evidence why vehicle is holed up / laying low */}
                <div className="space-y-2">
                  <span className="text-xs font-bold text-red-300 font-mono uppercase flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-red-400" />
                    <span>PROVENANCE: WHY SUSPECTS ARE CURRENTLY LAYING LOW HERE</span>
                  </span>

                  <ul className="space-y-1.5 text-xs text-stone-300 font-sans">
                    {currentCase.containmentZone.reasonsLayingLow.map((reason, idx) => (
                      <li key={idx} className="flex items-start gap-2 bg-black/60 p-2 rounded border border-red-500/20">
                        <span className="text-red-400 font-bold font-mono shrink-0">[{idx + 1}]</span>
                        <span>{reason}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Perimeter Boundary Cameras Cleared Negative */}
                <div className="space-y-2 bg-black/70 p-3 rounded-lg border border-white/10">
                  <span className="text-[11px] font-bold text-cyan-400 uppercase font-mono block">
                    PERIMETER CAMERAS SCANNED NEGATIVE (NO FURTHER EGRESS):
                  </span>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                    {currentCase.perimeterBoundaryCameras.map((pCam) => (
                      <div
                        key={pCam.cameraId}
                        className="p-2 rounded bg-black/60 border border-emerald-500/30 flex items-center justify-between"
                      >
                        <div className="min-w-0">
                          <span className="font-bold text-white block truncate text-[11px]">
                            {pCam.intersection}
                          </span>
                          <span className="text-[10px] text-stone-400">
                            FAST Cam #{pCam.cameraNumber} • {pCam.distanceMiles} mi away
                          </span>
                        </div>
                        <span className="text-[10px] font-bold text-emerald-400 font-mono bg-emerald-950 px-1.5 py-0.5 rounded border border-emerald-500/40">
                          CLEARED
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Recommended Tactical Surveillance Chokepoints */}
                <div className="space-y-2">
                  <span className="text-xs font-bold text-amber-300 uppercase font-mono flex items-center gap-1.5">
                    <MapPin className="w-3.5 h-3.5 text-amber-400" />
                    <span>RECOMMENDED PERIMETER CHOKEPOINTS & INTERCEPT UNITS</span>
                  </span>

                  <div className="space-y-2">
                    {currentCase.containmentZone.recommendedSurveillancePosts.map((post, idx) => (
                      <div
                        key={idx}
                        className="p-2.5 rounded bg-black/80 border border-amber-500/30 text-xs flex flex-col sm:flex-row sm:items-center justify-between gap-2"
                      >
                        <div>
                          <div className="font-bold text-white flex items-center gap-2">
                            <span className="text-amber-400 font-mono">[{post.label}]</span>
                            <span>{post.intersection}</span>
                          </div>
                          <div className="text-[11px] text-stone-300 font-sans mt-0.5">
                            {post.action}
                          </div>
                        </div>

                        <span className="text-[10px] text-stone-400 font-mono shrink-0 bg-white/5 px-2 py-1 rounded">
                          {post.coordinates.lat.toFixed(4)}, {post.coordinates.lng.toFixed(4)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Actionable Dispatches & Copy Report */}
                <div className="flex flex-col sm:flex-row items-center justify-between gap-2 pt-2 border-t border-red-500/30">
                  <div className="text-[11px] text-stone-400">
                    Coordinates: {currentCase.containmentZone.centerCoordinates.lat},{" "}
                    {currentCase.containmentZone.centerCoordinates.lng} ({currentCase.containmentZone.radiusMiles} mi radius)
                  </div>

                  <button
                    type="button"
                    onClick={handleCopyTacticalReport}
                    className="w-full sm:w-auto px-4 py-2 rounded-lg bg-red-600 hover:bg-red-500 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-[0_0_15px_rgba(239,68,68,0.4)] transition-all"
                  >
                    {copiedReport ? (
                      <>
                        <Check className="w-4 h-4" />
                        <span>TACTICAL REPORT COPIED</span>
                      </>
                    ) : (
                      <>
                        <Share2 className="w-4 h-4" />
                        <span>DISPATCH / BROADCAST REPORT</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
